### ISSUE TITLE
arduino-sht dependency

### ISSUE THREAD

**Issue by leloup314** [SiLab-Bonn/n2_cooling#3]
The firmware depends on the `arduino-sht` library. Maybe you could

- Add [arduino-sht](https://github.com/Sensirion/arduino-sht) as a [submodule](https://git-scm.com/book/de/v2/Git-Tools-Submodule) to the `firmware` folder

or

- Link the arduino-sht library as a dependency in the installation instructions

**Comment by houlahb** [comment]
Yes  I forgot to clean up the firmware. This will be added along with  a new Readme.txt and a short manual on how to use the system. Thanks
